import msgspec
from typing import Annotated


# RSA (Responsive Search Ad) Models for AI Generation
# Google Ads Constraints:
# - Headlines: 3-15 items, max 30 characters each
# - Descriptions: 2-4 items, max 90 characters each

Headline = Annotated[str, "Google Ads headline (max 30 chars)"]
Description = Annotated[str, "Google Ads description (max 90 chars)"]


class RSAAsset(msgspec.Struct):
    """
    Responsive Search Ad assets generated by AI.
    """
    headlines: list[Headline]
    descriptions: list[Description]
    path1: str | None = None  # Optional URL path (max 15 chars)
    path2: str | None = None  # Optional URL path (max 15 chars)


class GenerateAssetsRequest(msgspec.Struct):
    """
    Request to generate RSA assets via Gemini.
    """
    landing_page_url: str
    target_keywords: list[str]
    brand_voice: str | None = None  # e.g., "professional", "playful"
    language: str = "de"  # ISO 639-1 code

from typing import Optional, List
from app.domain.shared.models import ArangoDocument, EntityStatus, AdType

class Campaign(ArangoDocument):
    """
    Campaign Vertex.
    """
    customer_id: str
    name: str
    status: EntityStatus
    advertising_channel_type: str
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    
    # Local/Sync Fields
    sync_status: str = "synced"
    is_dirty: bool = False
    internal_notes: Optional[str] = None

class AdAssetLink(msgspec.Struct):
    """
    Edge representation for Ad -> Asset.
    """
    asset_text: str  # Denormalized
    asset_id: str
    field_type: str  # HEADLINE, DESCRIPTION
    pinned_field: Optional[str] = None
    performance_label: Optional[str] = None

class AdResponse(ArangoDocument):
    """
    Ad Vertex (augmented with nested assets for API).
    """
    ad_group_id: str
    final_urls: List[str]
    type: AdType
    headlines: List[AdAssetLink] = []
    descriptions: List[AdAssetLink] = []
